<?php require('template/header.phtml') ?>

<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3"><?php echo $view->pageTitle; ?>
    <small> </small>
</h1>

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="index.php">Home</a>
    </li>
    <li class="breadcrumb-item active"><?php echo $view->pageTitle; ?></li>
</ol>

<!-- Search bar -->
<!--<div class="breadcrumb">
    <div class="searchBar">-->
        <!--<p>You can search item lot by Lot Title, Lot Main or Auction.</p>
        <form action="<?php /*$_SERVER['PHP_SELF'] */?>" method="post">-->
            <!--<input type="text" name="searchBar" value="<?php /*if (isset($view->currentSearchItem)) {echo $view->currentSearchItem;} */?>" placeholder="search. . .">
            <input type="hidden" name="saveSearch" value="<?php /*if (isset($view->currentSearchItem)) {$view->currentSearchItem;} */?>">
            <button type="submit" name="searchButton" class="btn btn-info">Search</button>
            <?php /*if (isset($_SESSION['searchMode'])) : */?>
                <button type="submit" name="clearSearch" class="btn btn-danger">Clear</button>
                <br />
                <div>
                    <input type="hidden" name="pageLimit" value="<?php /*if (isset($view->currentLimit)) {echo $view->currentLimit;} */?>">
                    <input type="hidden" name="savePageLimit" value="<?php /*if (isset($view->currentLimit)) {echo $view->currentLimit;} */?>">
                </div>
                <br />
            --><?php /*endif; */?>

            <!-- Filters -->
            <!--<div>
                <label>Filter: </label>
                <select name="filters">
                    <option value="<?php /*if (isset($view->filter)) {echo $view->filter;}*/?>">-</option>
                    <option value="ascendingOrder">A - Z</option>
                    <option value="descendingOrder">Z - A</option>
                    <option value="popular">Most Popular</option>
                    <option value="recent">Most Recent</option>
                </select>
                <input type="hidden" name="filterOption" value="<?php /*if (isset($view->filter)) {echo $view->filter;}*/?>">
                <?php /*if (isset($_SESSION['searchMode'])) : */?>
                    <button type="submit" name="clearFilter" class="btn btn-secondary">Clear</button>
                <?php /*endif; */?>
            </div>-->
            <div><p class="error"><?php if (isset($view->error)) {echo $view->error;} ?></p></div>
<!--    </div>
</div>-->

<div class="page">
    <div>
    <p><i><?php if (isset($view->totalRecords)) {echo 'Total - ' . $view->totalRecords;} ?>
    <?php if (isset($_GET['page'])) {
                echo 'Page ' . $_GET['page'];
            }
        else
        {
            echo 'Page 1';
        }?></i></p>
    </div>
    <div>
        <label>Relevance</label>
        <select id="filters" name="filters">
            <option id="none" value="<?php if (isset($view->filter)) {echo $view->filter;}?>">-</option>
            <option id="ascendingOrder" value="ascendingOrder">A - Z</option>
            <option id="descendingOrder" value="descendingOrder">Z - A</option>
            <option id="popular" value="popular">Most Popular</option>
            <option id="recent" value="recent">Most Recent</option>
        </select>
    </div>
</div>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <input type="hidden" name="saveAuctionName" value="<?php if (isset($view->nameOfAuction)) {echo $view->nameOfAuction;} ?>">
    <br>

    <!-- Listings -->
    <div id="listing" class="row">
        <div class="col-sm-4">
            <h4>Category</h4>
            <div>
                <div>
                    <input type="checkbox" name="category" value="Most Popular">
                    <label>Cars</label>
                </div>
                <div>
                    <input type="checkbox" name="category" value="Most Popular">
                    <label>Watches</label>
                </div>
                <div>
                    <input type="checkbox" name="category" value="Most Popular">
                    <label>Paintings</label>
                </div>
                <div>
                    <input type="checkbox" name="category" value="Most Popular">
                    <label>Artifacts</label>
                </div>
                <div>
                    <input type="checkbox" name="category" value="Most Popular">
                    <label>Jewelry</label>
                </div>
            </div>
        </div>
        <?php $num = 1;
        foreach ($view->auctionItem as $auctionItemData) {
            // echo $num;
            echo '<div class="col-lg-6 portfolio-item"><form action="" method="post"><div id="auctionLotContainer' . $num .'" class="card h-100">' .
                '<h4 id="cardHeader' . $num .'" class="card-header">Lot ID #' . $auctionItemData->getLotID() .
                ': ' . $auctionItemData->getLotTitle() . ' - ' . $auctionItemData->getLotMain() . '</h4>' .
                '<img id="cardImage' . $num .'" src="images/' . $auctionItemData->getImage() . '.jpg">' .
                '<div id="cardBody' . $num .'" class="card-body">' .
                '<h5><b>' . $auctionItemData->getAuctionName() . '</b>  <span id="liveTxt'. $num .'"></span></h5>' .
                '<p class="card-text">' . $auctionItemData->getDescription() . '</p>' .
                '<p class="card-text"><b>Opening bid Price: £' . $auctionItemData->getPrice() . '</b></p>' .
                '<p style="color: #4e555b"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                    </svg><b><i>' . $auctionItemData->getLocation() . '</i></b></p>' .
                '<p id="startTime' . $num .'" style="color: #4e555b"><b><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar3" viewBox="0 0 16 16">
                    <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                    <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                    </svg> ' . $auctionItemData->getDatetime() . ' GMT</b></p>' .
                '<p id="countDownTimer' . $num .'"></p>' .
                '<p id="endDateTxt' . $num .'"></p>' .
                '<input id="lot_id' . $num .'" type="hidden" name="lotID" value="' . $auctionItemData->getLotId() . '">' .
                '<input id="start'. $num .'" type="hidden" name="auctionDatetime" value="' . $auctionItemData->getDatetime() . '">' .
                '<input id="endDateTime'. $num .'" type="hidden" name="auctionEndDatetime" value="' . $auctionItemData->getEndDatetime() . '">' .
                '<input id="trackCount' . $num .'" type="hidden" name="auctionAdmin" value="' . $num . '">' .
                '</div><div class="card-footer"><input type="submit" name="view" value="View" class="btn btn-primary"/></div></div>' .
                '<input type="hidden" name="lotTitle" value="' . $auctionItemData->getLotTitle() . '">' .
                '<input type="hidden" name="lotMain" value="' . $auctionItemData->getLotMain() . '">' .
                '<input type="hidden" name="lotImage" value="' . $auctionItemData->getImage() . '.jpg">' .
                '<input type="hidden" name="lotDescription" value="' . $auctionItemData->getDescription() . '">' .
                '<input type="hidden" name="lotPrice" value="' . $auctionItemData->getPrice() . '">' .
                '<input type="hidden" name="auctionID" value="' . $auctionItemData->getAuctionID() . '">' .
                '<input type="hidden" name="auctionName" value="' . $auctionItemData->getAuctionName() . '">' .
                '<input type="hidden" name="auctionLocation" value="' . $auctionItemData->getLocation() . '">' .
                '<input type="hidden" name="auctionAdmin" value="' . $view->auctionItemDateSet->getAuctionAdmin(intval($auctionItemData->getUserID())) . '">' .
                '</form></div>';
            $num++;
        }?>
    </div>
    <br />
    <script type="text/javascript">
        function FetchAllLots(filter)
        {
            let xmlhttp = new XMLHttpRequest();

            xmlhttp.onreadystatechange = function ()
            {
                if (xmlhttp.readyState == 4 && xmlhttp.status == 200)
                {
                    // console.log(JSON.parse(this.responseText));
                    let auctionLots = JSON.parse(this.responseText);

                    let counter = 1;
                    auctionLots.forEach(function (obj){
                        let header = document.getElementById("cardHeader" + counter);
                        let img = document.getElementById("cardImage" + counter);
                        let body = document.getElementById("cardBody" + counter);

                        header.innerHTML = "Lot ID#" + obj._lotID + ": " + obj._lot_title +
                            " - " + obj._lot_main;
                        img.src = "images/" + obj._image + ".jpg";
                        body.innerHTML = "<h5><b>" + obj._auction_name + " <span id='liveTxt" + counter + "'></span></b></h5>" +
                            "<p class='card-text'>" + obj._description + "</p>" +
                            "<p class='card-text'>Opening bid Price: £" + obj._price + "</p>" +
                            "<p style='color: #4e555b'><svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-geo-alt-fill' viewBox='0 0 16 16'> " +
                            "<path d='M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z'/></svg><b><i>" +
                            obj._location + "</i></b></p>" +
                            "<p id='startTime" + counter + "' style='color: #4e555b'><b><svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-calendar3' viewBox='0 0 16 16'> " +
                            "<path d='M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z'/> " +
                            "<path d='M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z'/>" +
                            "</svg>" + obj._datetime + " GMT</b></p>" +
                            "<p id='countDownTimer" + counter + "'></p>" +
                            "<p id='endDateTxt" + counter + "'></p>" +
                            "<input id='lot_id" + counter + "' type='hidden' name='lotID' value='" + obj._lotID + "'>" +
                            "<input id='start" + counter + "' type='hidden' name='lotID' value='" + obj._datetime + "'>" +
                            "<input id='endDateTime" + counter + "' type='hidden' name='lotID' value='" + obj._endDatetime + "'>" +
                            "<input id='trackCount" + counter + "' type='hidden' name='lotID' value='" + counter + "'>";
                        counter++;
                    });


                }
            }

            xmlhttp.open("GET", "ajax/fetchAllLots.php?q=" + filter, true);
            xmlhttp.send();
        }

        let total = <?php echo $view->totalRecords;?>; // Total number of lots
        let limit = total >= 20 ? 20: total; // Total number of lots to display per page

        let filters = document.getElementById("filters");
        let recentFilter = document.getElementById("recent");
        let popularFilter = document.getElementById("popular");
        // console.log(filters);

        function filterLots()
        {
            let selectedFilter = "";
            if (recentFilter.selected)
            {
                selectedFilter = recentFilter.value;
                // var a = new FetchAllLots(selectedFilter);
            }
            var a = new FetchAllLots(selectedFilter);

            // for (let i = 1; i <= limit; i++)
            // {
            //     let cardHeader = document.getElementById("cardHeader" + i);
            //     let cardImage = document.getElementById("cardImage" + i);
            //     let cardBody = document.getElementById("cardBody" + i);
            //
            //     console.log(cardHeader);
            //
            //     var a = new FetchAllLots(selectedFilter, cardHeader, cardImage, cardBody);
            // }
        }

        // filters.addEventListener('click', new FetchAllLots("recent"), true);
    </script>

    <script type="text/javascript" src="js/countDownTimer.js"></script>
    <script type="text/javascript">
        for (let i = 1; i <= limit; i++)
        {
            let start = document.getElementById("start" + i).value;
            let endDate = document.getElementById("endDateTime" + i).value;
            let timer = document.getElementById("countDownTimer" + i);
            let liveTxt = document.getElementById("liveTxt" + i);
            let endDateTxt = document.getElementById("endDateTxt" + i);
            let startTime = document.getElementById("startTime" + i);

            var x = new CountDown(start, endDate, timer, liveTxt, endDateTxt, startTime); // CountDown instance
        }
    </script>

    <!-- Pagination -->
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="<?php if (isset($view->previous)) {echo $view->previous;} ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            <li class="page-item">
                <?php
                if (isset($view->currentPage)) {
                    for ($page = $_GET['page'] - $view->currentPage; ($page <= $_GET['page'] + $view->currentPage) && ($page < $view->totalPages + 1); $page++) {

                        if ($page == 1)
                        {
                            $pageLimit = $view->totalPages >= 5 ? 5: $view->totalPages;
                            for ($j = 1; $j < $pageLimit; $j++)
                            {
                                // $token = $_SESSION['token'];
                                echo '<div style="display: inline-block;"><a class="page-link" href="auctionItem.php?page=' . $page . '&t=' . $_SESSION['token'] .'">' . $page . '</a></div>';
                                $page++;
                                $_SESSION['auctionItem'] = true;
                            }
                        }

                        echo '<div style="display: inline-block;"><a class="page-link" href="auctionItem.php?page=' . $page . '&t=' . $_SESSION['token'] .'">' . $page . '</a></div>';
                        $_SESSION['auctionItem'] = true;
                    }
                }
                ?>
            </li>
            <li class="page-item">
                <a class="page-link" href="<?php if (isset($view->next)) {echo $view->next;};?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>

<?php require('template/footer.phtml') ?>
