<?php require('template/header.phtml') ?>

<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3"><?php echo $view->pageTitle; ?>
    <small> </small>
</h1>

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="index.php">Home</a>
    </li>
    <li class="breadcrumb-item active"><?php echo $view->pageTitle; ?></li>
</ol>

<!-- Search bar -->
<div class="breadcrumb">
    <div class="searchBar">
        <p>You can search item lot by Lot Title, Lot Main or Auction.</p>
        <form action="<?php $_SERVER['PHP_SELF'] ?>" method="post">
            <input type="text" name="searchBar" value="<?php if (isset($view->currentSearchItem)) {echo $view->currentSearchItem;} ?>" placeholder="search. . .">
            <input type="hidden" name="saveSearch" value="<?php if (isset($view->currentSearchItem)) {$view->currentSearchItem;} ?>">
            <button type="submit" name="searchButton" class="btn btn-info">Search</button>
            <?php if (isset($_SESSION['searchMode'])) : ?>
                <button type="submit" name="clearSearch" class="btn btn-danger">Clear</button>
                <br />
                <div>
                    <?php /*for ($i = 1; $i <   $view->totalPages; $i++)
                {
                    echo '<button type="submit" name="page">'. $i .'</button>';
                }*/?>
                    <input type="hidden" name="pageLimit" value="<?php if (isset($view->currentLimit)) {echo $view->currentLimit;} ?>">
                    <input type="hidden" name="savePageLimit" value="<?php if (isset($view->currentLimit)) {echo $view->currentLimit;} ?>">
                    <!--<button id="loadPages" type="submit" name="morePages" class="btn btn-primary">Load more results</button>
                    <button id="lessPages" type="submit" name="lessPages" class="btn btn-primary">few results</button>-->
                </div>
                <br />
            <?php endif; ?>

            <!-- Filters -->
            <div>
                <label>Filter: </label>
                <select name="filters">
                    <option value="<?php if (isset($view->filter)) {echo $view->filter;}?>">-</option>
                    <option value="ascendingOrder">A - Z</option>
                    <option value="descendingOrder">Z - A</option>
                    <option value="popular">Most Popular</option>
                    <option value="recent">Most Recent</option>
                </select>
                <input type="hidden" name="filterOption" value="<?php if (isset($view->filter)) {echo $view->filter;}?>">
                <?php if (isset($_SESSION['searchMode'])) : ?>
                    <button type="submit" name="clearFilter" class="btn btn-secondary">Clear</button>
                <?php endif; ?>
            </div>
            <div><p class="error"><?php if (isset($view->error)) {echo $view->error;} ?></p></div>
    </div>
</div>

<div class="page">
    <p><i><?php if (isset($view->totalRecords)) {echo 'Total - ' . $view->totalRecords;} ?>
    <?php if (isset($_GET['page'])) {
                echo 'Page ' . $_GET['page'];
            }
        else
        {
            echo 'Page 1';
        }?></i></p>
</div>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <input type="hidden" name="saveAuctionName" value="<?php if (isset($view->nameOfAuction)) {echo $view->nameOfAuction;} ?>">
    <br>

    <!-- Listings -->
    <div id="listing" class="row">
        <?php foreach ($view->auctionItem as $auctionItemData) {
            echo '<div class="col-lg-6 portfolio-item"><form action="" method="post"><div class="card h-100">' .
                '<h4 class="card-header">Lot ID #' . $auctionItemData->getLotID() .
                ': ' . $auctionItemData->getLotTitle() . ' - ' . $auctionItemData->getLotMain() . '</h4>' .
                '<img src="images/' . $auctionItemData->getImage(). '.jpg">' .
                '<input type="hidden" name="lotImage" value="'. $auctionItemData->getImage() . '.jpg">' .
                '<div class="card-body">' .
                '<h5><b>' . $auctionItemData->getAuctionName() . '</b></h5>' .
                '<p class="card-text">' . $auctionItemData->getDescription() . '</p>' .
                '<p class="card-text"><b>Opening bid Price: £' . $auctionItemData->getPrice() . '</b></p>' .
                '<p style="color: #4e555b"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                    </svg><b><i>' . $auctionItemData->getLocation() .'</i>   -   ' . $auctionItemData->getDatetime() .' GMT</b></p>' .
                '<input type="hidden" name="lotID" value="'. $auctionItemData->getLotId() . '">' .
                '<input type="hidden" name="lotTitle" value="'. $auctionItemData->getLotTitle() . '">' .
                '<input type="hidden" name="lotMain" value="'. $auctionItemData->getLotMain() . '">' .
                '<input type="hidden" name="lotDescription" value="'. $auctionItemData->getDescription() . '">' .
                '<input type="hidden" name="lotPrice" value="'. $auctionItemData->getPrice() . '">' .
                '<input type="hidden" name="auctionID" value="'. $auctionItemData->getAuctionID() . '">' .
                '<input type="hidden" name="auctionName" value="'. $auctionItemData->getAuctionName() . '">' .
                '<input type="hidden" name="auctionLocation" value="'. $auctionItemData->getLocation() . '">' .
                '<input type="hidden" name="auctionDatetime" value="'. $auctionItemData->getDatetime() . '">' .
                '<input type="hidden" name="auctionAdmin" value="'. $view->auctionItemDateSet->getAuctionAdmin(intval($auctionItemData->getUserID())) . '">' .
                '</div><div class="card-footer"><input type="submit" name="view" value="View" class="btn btn-primary"/></div></div></form></div>';
        }?>
    </div>
    <br />

    <!-- Pagination -->
    <?php /*if (!isset($_SESSION['searchMode'])) : */?>

        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="<?php if (isset($view->previous)) {echo $view->previous;} ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            <li class="page-item">
                <?php
                if (isset($view->currentPage)) {
                    for ($page = $_GET['page'] - $view->currentPage; ($page <= $_GET['page'] + $view->currentPage) && ($page < $view->totalPages + 1); $page++) {
                        if ($page == 1)
                        {
                            for ($j = 1; $j < 5; $j++)
                            {
                                echo '<div style="display: inline-block;"><a class="page-link" href="auctionItem.php?page=' . $page . '">' . $page . '</a></div>';
                                $page++;
                                $_SESSION['auctionItem'] = true;
                            };
                        }

                        echo '<div style="display: inline-block;"><a class="page-link" href="auctionItem.php?page=' . $page . '">' . $page . '</a></div>';
                        $_SESSION['auctionItem'] = true;
                    }
                }
                ?>
            </li>
            <li class="page-item">
                <a class="page-link" href="<?php if (isset($view->next)) {echo $view->next;};?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    <?php /*endif; */?>

<?php require('template/footer.phtml') ?>
