<?php require('template/header.phtml') ?>

<!-- Slideshow -->
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div class="carousel-item active" style="background-image: url('images/supercarCoverImage.jpg')">
                <div class="carousel-caption d-none d-md-block">
                    <h3 style="color: #000000;"><b>First Slide</b></h3>
                    <p style="color: #000000;"><b>This is a description for the first slide.</b></p>
                </div>
            </div>
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('images/Watches9.jpg')">
                <div class="carousel-caption d-none d-md-block">
                    <h3>First Slide</h3>
                    <p>This is a description for the first slide.</p>
                </div>
            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('images/ArtifactCoverImage.jpg')">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Second Slide</h3>
                    <p>This is a description for the second slide.</p>
                </div>
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('images/auctionCover.jpg')">
                <div class="carousel-caption d-none d-md-block">
                    <h3 style="color: #000000;">Third Slide</h3>
                    <p style="color: #000000;">This is a description for the third slide.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>

<h1 class="my-4"><b><u>Welcome to Salford Auctions!</u></b></h1>
<br />
<form action="" method="post">
<div class="row" id="listing">
    <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header">Super Cars</h4>
            <img src="images/supercar7.jpg">
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
                <button name="SuperCar" class="btn btn-primary" >Learn More</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header">Artifacts</h4>
            <img src="images/Artifact1.jpg">
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae atque exercitationem ut consequuntur, sed eveniet, magni nostrum sint fuga.</p>
            </div>
            <div class="card-footer">
                <button name="Artifacts" class="btn btn-primary">Learn More</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header">Jewelry</h4>
            <img src="images/Jewelry4.jpg">
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
                <button name="Jewelry" class="btn btn-primary">Learn More</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header">Paintings</h4>
            <img src="images/Painting5.jpg">
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
                <button name="Paintings" class="btn btn-primary">Learn More</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header">Watches</h4>
            <img src="images/Watches4.jpg">
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
                <button name="Watches" class="btn btn-primary">Learn More</button>
            </div>
        </div>
    </div>
</div>
</form>
<!-- /.row -->

<hr>

<!-- Call to Action Section -->
<div class="row mb-4">
    <div class="col-md-8">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
    </div>
    <div class="col-md-4">
        <a class="btn btn-lg btn-secondary btn-block" href="auctionItem.php">View All listings</a>
    </div>
</div>
<?php require('template/footer.phtml') ?>
