<?php require_once ('template/header.phtml') ?>

<style>
    #listBody {
        background-color: #e6e6e6;
    }

    #listHeader {
        padding: 5px 2px;
        background-color: #343a40;
        color: #fff3cd;
    }
</style>

<div>
<!--    <table class="table table-active">
        <thead>
            <th>Lot</th>
            <th>Auction</th>
            <th>Your Bid</th>
            <th>Status</th>-->
            <p class="error"><b><?php if (isset($view->error)) {echo $view->error;} ?></b></p>
<!--        </thead>
        <tbody>-->
            <?php if (!$view->bidItemDataSet)
            {
                echo  $view->bidError;
                }
                else
                {
                    if (isset($view->bidStatus))
                    {
                        echo '<h3>' . $view->bidStatus . '</h3>';
                    }
                    foreach ($view->bidItemDataSet as $bidItem)
                    {
                        /*echo '<form action="" method="post">' .
                            '<tr><td><p>' . $bidItem->getLotID() . '. ' . '<input type="hidden" name="lotID" value="' . $bidItem->getLotID() . '">' .
                            $bidItem->getLotTitle() . '<input type="hidden" name="lotTitle" value="' . $bidItem->getLotTitle() . '">' .
                            ', ' . $bidItem->getLotMain() . '<input type="hidden" name="lotMain" value="' . $bidItem->getLotMain() . '">' .
                            '</p><img src="../images/' . $bidItem->getLotImage() . '.jpg" alt="Image not found">' .
                            '<input type="hidden" name="lotImage" value="' . $bidItem->getLotImage() . '.jpg">' .
                            '</td><td><p>' . $bidItem->getAuctionID() . '. ' . '<input type="hidden" name="auctionID" value="' . $bidItem->getAuctionID() . '">' .
                            $bidItem->getAuctionName() . '<input type="hidden" name="auctionName" value="' . $bidItem->getAuctionName() . '">' .
                            '</p><p>' . $bidItem->getAuctionLocation() . '<input type="hidden" name="auctionLocation" value="' . $bidItem->getAuctionLocation() . '">' .
                            ',</p><p>' . $bidItem->getAuctionDatetime() .'</p>' . '<input type="hidden" name="auctionDatetime" value="' . $bidItem->getAuctionDatetime() . '">' .
                            '<input type="hidden" name="bidID" value="' . $bidItem->getBidID() . '">' .
                            '</td><td>' . '£' . $bidItem->getBid() . '<input type="hidden" name="bid" value="' . $bidItem->getBid() . '">' .
                            '</td><td>' . '<div class="button"><input type="submit" name="statusButton" value="Check" class="btn btn-secondary"></div>' .
                            '</td><td>' . '<div><label>£</label><input type="text" name="newBid" placeholder="1000"></div><div class="button"><input type="submit" name="editBid" value="Edit" class="btn btn-primary"></div>' .
                            '<div class="button"><input type="submit" name="removeBid" value="X" class="btn btn-danger"></div>' .
                            '</td></tr></form>';
                    }}*/
                        echo '<form action="" method="post"><div class="listContainer"><div id="listHeader" class="row"><div class="col-sm-11"><h3>#' .
                            $bidItem->getLotID() . ': ' . $bidItem->getLotTitle() . ' - ' .
                            $bidItem->getLotMain() . '</h3></div><div class="col-sm-1">
                            <input type="submit" name="removeBid" value="X" class="btn btn-danger"></div>
                            </div><div id="listBody" class="row"><div class="col-sm-5">' .
                            '<img src="images/' . $bidItem->getLotImage() . '.jpg" alt="Image not found">' .
                            '<input type="hidden" name="lotImage" value="' . $bidItem->getLotImage() . '.jpg">' .
                            '<input type="hidden" name="lotID" value="' . $bidItem->getLotID() . '">' .
                            '<input type="hidden" name="lotTitle" value="' . $bidItem->getLotTitle() . '">' .
                            '<input type="hidden" name="lotMain" value="' . $bidItem->getLotMain() . '">' .
                            '</div><div class="col-md-6"><p><b>' . $bidItem->getAuctionID() . ' - ' . $bidItem->getAuctionName() . '</b></p>' .
                            '<input type="hidden" name="auctionID" value="' . $bidItem->getAuctionID() . '">' .
                            '<input type="hidden" name="auctionName" value="' . $bidItem->getAuctionName() . '">' .
                            '<p>' . $bidItem->getAuctionLocation() . '</p>' . '<input type="hidden" name="auctionLocation" value="' . $bidItem->getAuctionLocation() . '">' .
                            '<p>' . $bidItem->getAuctionDatetime() . '</p>' . '<input type="hidden" name="auctionDatetime" value="' . $bidItem->getAuctionDatetime() . '">' .
                            '<p><b>Your Bid: </b>£' . $bidItem->getBid() . '</p>' . '<input type="hidden" name="bid" value="' . $bidItem->getBid() . '">' .
                            '<label>£</label><input type="text" name="newBid" placeholder="1000">' .
                            '<div><input type="submit" name="editBid" value="Edit" class="btn btn-primary">
                             <input type="submit" name="statusButton" value="Check" class="btn btn-secondary"></div>' .
                            '</div></div></div></form>';
                    }}?>
<!--        </tbody>
    </table>-->
</div>
<br />

<?php require_once ('template/footer.phtml') ?>
