<?php require_once ('template/header.phtml') ?>

<style>
    #listBody {
        background-color: #e6e6e6;
    }

    #listHeader {
        padding: 5px 2px;
        background-color: #343a40;
        color: #fff3cd;
    }
</style>

<div>
<!--    <table class="table table-active">
        <thead>
            <th>Lot</th>
            <th>Auction</th>
            <th>Your Bid</th>
            <th>Status</th>-->

    <h1 class="mt-4 mb-3"><?php echo $view->pageTitle; ?>
        <small> </small>
    </h1>

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.php">Home</a>
        </li>
        <li class="breadcrumb-item active"><?php echo $view->pageTitle; ?></li>
    </ol>

            <p class="error"><b><?php if (isset($view->error)) {echo $view->error;} ?></b></p>
<!--        </thead>
        <tbody>-->
            <?php if (!$view->bidItemDataSet)
            {
                echo  $view->bidError;
                }
                else
                {
                    if (isset($view->bidStatus))
                    {
                        echo '<h3>' . $view->bidStatus . '</h3>';
                    }

                    $num = 1;
                    foreach ($view->bidItemDataSet as $bidItem)
                    {
                        // var_dump($view->currentDate > $bidItem->getAuctionEndDatetime());
                        // var_dump($bidItem->getAuctionEndDatetime());
                        echo '<form action="" method="post"><div class="listContainer"><div id="listHeader" class="row"><div class="col-sm-11"><h3>#' .
                            $bidItem->getLotID() . ': ' . $bidItem->getLotTitle() . ' - ' .
                            $bidItem->getLotMain() . '</h3></div><div class="col-sm-1">';

                        if ($view->currentDate > $bidItem->getAuctionEndDatetime())
                            echo '<input id="removeBtn'. $num .'" type="submit" name="removeBid" value="X" class="btn btn-danger">';

                        echo '</div></div><div id="listBody" class="row"><div class="col-sm-5">' .
                            '<img src="images/' . $bidItem->getLotImage() . '.jpg" alt="Image not found">' .
                            '<input type="hidden" name="lotImage" value="' . $bidItem->getLotImage() . '.jpg">' .
                            '<input id="lot_id'. $num .'" type="hidden" name="lotID" value="' . $bidItem->getLotID() . '">' .
                            '<input type="hidden" name="lotTitle" value="' . $bidItem->getLotTitle() . '">' .
                            '<input type="hidden" name="lotMain" value="' . $bidItem->getLotMain() . '">' .
                            '</div><div class="col-md-6"><p><b>' . $bidItem->getAuctionID() . ' - ' . $bidItem->getAuctionName() . '</b></p>' .
                            '<input type="hidden" name="auctionID" value="' . $bidItem->getAuctionID() . '">' .
                            '<input type="hidden" name="auctionName" value="' . $bidItem->getAuctionName() . '">' .
                            '<p>' . $bidItem->getAuctionLocation() . '</p>' . '<input type="hidden" name="auctionLocation" value="' . $bidItem->getAuctionLocation() . '">' .
                            '<p>' . $bidItem->getAuctionDatetime() . '</p>' . '<input type="hidden" name="auctionDatetime" value="' . $bidItem->getAuctionDatetime() . '">' .
                            '<input id="auctionEndDatetime'. $num .'" type="hidden" name="auctionEndDatetime" value="' . $bidItem->getAuctionEndDatetime() . '">' .
                            '<p><b>Your Bid: </b>£' . $bidItem->getBid() . '  <span id="bidStatus' . $num .'" style="display: inline-block; padding: 5px;" class="btn-success"></span></p>' .
                            '<input id="userBid'. $num .'" type="hidden" name="bid" value="' . $bidItem->getBid() . '">' .
                            '<input type="hidden" name="bidID" value="' . $bidItem->getBidID() . '">' .
                            '<label>£</label><input type="text" name="newBid" placeholder="1000">' .
                            '<div><input type="submit" name="editBid" value="Edit" class="btn btn-primary">
                             <!--<input type="submit" name="statusButton" value="Check" class="btn btn-secondary">-->
                             <input type="submit" name="viewItem" value="View" class="btn btn-info" </div>' .
                            '</div></div></div><br /></form>' .
                            '<script type="text/javascript" src="js/bidStatus.js"></script>';
                        $num++;
                    }}?>
<!--        </tbody>
    </table>-->
</div>
<br />
<script type="text/javascript" src="js/bidStatus.js"></script>
<script type="text/javascript">
    var totalBid = <?php echo count($view->bidItemDataSet) ?>;
    // console.log(totalBid);

    for (let i = 1; i <= totalBid; i++)
    {
        var x = new UserBidStatus(document.getElementById("bidStatus" + i), document.getElementById("lot_id" + i).value)
    }

    // let today = new Date().getTime();

    // let todayDate = today.getFullYear() + "-" + today.getMonth() + "-" + today.getDate();
    // let time = today.getHours() + ":" + today.getMinutes();
    // let todayDatetime = todayDate + " " + time;

    //for (let i = 1; i < <?php //echo $num; ?>//; i++)
    //{
    //    let auctionEndDatetime = new Date(document.getElementById("auctionEndDatetime" + i).value).getTime();
    //    console.log(auctionEndDatetime.value);
    //    if (auctionEndDatetime < today)
    //    {
    //        document.getElementById("removeBtn" + i).type = "submit";
    //        console.log(auctionEndDatetime.value < today);
    //    }
    //}

</script>

<!--<script type="text/javascript" src="js/bidStatus.js">

    /*var bidStatus = document.getElementById("bidStatus");
    var userBid = document.getElementById("lot_id");*/

    /*function UserBidStatus(bidStatus, userBid)
    {
        var xmlhttp = new XMLHttpRequest();
        // console.log(userBid);
        // console.log(bidStatus);

        xmlhttp.onreadystatechange = function ()
        {
            if (this.readyState == 4 && this.status == 200)
            {
                // console.log(this.responseText);
                bidStatus.innerHTML = this.responseText;

                if (this.responseText == "Highest bid")
                {
                    bidStatus.style.backgroundColor = "green";
                }
                else if (this.responseText == "Outbid")
                {
                    bidStatus.style.backgroundColor = "red";
                }
            }
        }

        xmlhttp.open("GET", "ajax/getBidStatus.php?q=" + userBid, true);
        xmlhttp.send();
    }*/
    // let userBidStatus = new UserBidStatus(userBid.value, bidStatus);
    // document.window.addEventListener('click', new UserBidStatus(userBid, bidStatus), true);
</script>-->

<?php require_once ('template/footer.phtml') ?>
