<ul class="pagination justify-content-center">
    <li class="page-item">
        <a class="page-link" href="<?php if (isset($view->previous)) {echo $view->previous;} ?>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>
    <li class="page-item">
        <?php
        /*if (($_GET['page'] - 10) < 1)
        {
            $current = $_GET['page'] - 1;
        }
        else
        {
            $current = 10;
        }*/
        if (isset($view->currentPage)) {
            for ($page = $_GET['page'] - $view->currentPage; $page <= $_GET['page'] + $view->currentPage; $page++) {
                if ($page == 1)
                {
                    for ($j = 1; $j < 5; $j++)
                    {
                        echo '<div style="display: inline-block;"><a class="page-link" href="auctionItem.php?page=' . $page . '">' . $page . '</a></div>';
                        $page++;
                        $_SESSION['auctionItem'] = true;
                    };
                }
                echo '<div style="display: inline-block;"><a class="page-link" href="auctionItem.php?page=' . $page . '">' . $page . '</a></div>';
                $_SESSION['auctionItem'] = true;
            }
        }
        ?>
    </li>
    <!--<li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>-->
    <li class="page-item">
        <a class="page-link" href="<?php if (isset($view->next)) {echo $view->next;};?>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
</ul>
