<?php require ('template/header.phtml') ?>

<div id="RegistrationForm" class="container justify-content-center">

    <!-- Page Heading -->
    <h1 class="mt-4 mb-3"><?php echo $view->pageTitle; ?>
        <small> </small>
    </h1>

    <p>Please fill this form to create an account:</p>

    <form id="register_form" action="<?php $_SERVER['PHP_SELF'] ?>" method="post">

        <!-- Email Required -->
        <div class="form-group">
            <input type="text" name="registerEmail" placeholder="email" class="form-control form-control-sm" id="registerEmail">
        </div>

        <div class="form-group">
            <input type="text" name="registerUsername" placeholder="Username" value="<?php if (isset($view->newUser))
            {
                echo $view->newUser;
            }
            ?>" class="form-control form-control-sm" required="">
        </div>

        <div class="form-group">
            <input id="newPassword" type="password" name="registerPassword" placeholder="Password" class="form-control form-control-sm" required="" onkeyup="strength(this.value)">
        </div>

        <div id="passwordStrength" class="passwordCheck">
            <div id="weak"></div>
            <div id="fair"></div>
            <div id="strong"></div>
            <p id="passwordStatus">Strength</p>
        </div>

        <div class="form-group">
            <input type="password" name="confirmPassword" placeholder="Confirm password" class="form-control form-control-sm" required="">
        </div>

        <div id="code" class="justify-content-center rounded-pill">
            <div class="recaptcha"><b><?php if (isset($view->reCaptcha))
                    {
                        echo $view->reCaptcha;
                    }?>
                </b></div>
            <input type="text" name="code" placeholder="Code" class="justify-content-center">
            <input type="hidden" name="finalCode" value="<?php if (isset($view->reCaptcha))
            {
                echo $view->reCaptcha;
            }?>">
        </div>
        <br />
        <?php if (isset($view->error)) : ?>
            <div class="alert alert-danger" role="alert">
                <p><b>
                        <?php echo $view->error; ?>

                    </b></p>
            </div>
        <?php endif; ?>

        <div class="form-group">
            <button type="submit" name="register" class="btn btn-success btn-block">Register</button>
        </div>

        <div class="form-group text-center">
            Already registered?<a href="login.php"> Sign in here</a>
        </div>
        <!--<div class="form-group">
            <label class="control-label col-sm-2">Username:</label>
            <div class="col-sm-10">
                <input type="text" name="registerUsername" placeholder="username" value="<?php /*if (isset($view->newUser))
                {
                    echo $view->newUser;
                }
                */?>" required="required">
            </div>
        </div>
        <br />-->
        <!-- Email is required -->
        <!--<div class="form-group">
            <div class="col-sm-10">
                <input id="registerEmail" type="text" name="registerEmail" placeholder="username">
            </div>
        </div>
        <br />
        <div class="form-group">
            <label class="control-label col-sm-2">Password:</label>
            <div class="col-sm-10">
                <input type="password" name="registerPassword" placeholder="password">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Confirm Password:</label>
            <div class="col-sm-10">
                <input type="password" name="confirmPassword" placeholder="confirm password">
            </div>
            <div id="code" class="form-group">
                <label class="control-label col-sm-2"><?php /*if (isset($view->reCaptcha))
                    {
                        echo $view->reCaptcha;
                    }*/?></label>
                <div class="col-sm-10">
                    <input type="text" name="code" placeholder="Code" class="form-control">
                    <input type="hidden" name="finalCode" value="<?php /*if (isset($view->reCaptcha))
                    {
                        echo $view->reCaptcha;
                    }*/?>">
                </div>
            </div>
            <div class="button">
                <input type="submit" name="register" value="Sign up" class="btn btn-success"
                       maxlength="16" minlength="8">
            </div>-->

    </form>
</div>

<script type="text/javascript">
    var userPassword = document.getElementById("newPassword"); // text from new password field

    var weak = document.getElementById("weak"); // Weak strength container
    var fair = document.getElementById("fair"); // Fair strength container
    var strong = document.getElementById("strong"); // Strong strength container
    var status = document.getElementById("passwordStatus"); // password strength status text

    /**
     * Checks the strength of the password
     * @param str - value of new password field
     */
    function strength(str)
    {
        let fairStrength = /\d/g; // Fair password condition
        let strongStrength = /[A-Z]*[a-z]*[0-9]*[-+_!@#$%^&*.,?]/; // Strong password condition

        var changeColour = (element, colour) => {element.style.backgroundColor = colour;} // change the colour of element

        // Get all nodes inside element with id 'passwordStrength'
        var containers = document.getElementById("passwordStrength").children;
        for (var i = 0; i < containers.length - 1; i++)
        {
            containers[i].style.display = "inline-block"; // set child elements' display to inline block
        }
        // console.log(containers);

        // If user typed password length is less than 8
        if (str.length < 8)
        {
            changeColour(weak, "red");
            changeColour(fair, "#4e555b");
            changeColour(strong, "#4e555b");
            status.innerHTML = "Weak";
            // console.log(status.innerHTML);
        }

        // If user password has a number and greater than or equal to 8 characters
        if (fairStrength.test(str) && str.length >= 8)
        {
            changeColour(weak, "orange");
            changeColour(fair, "orange");
            changeColour(strong, "#4e555b");
            status.innerHTML = "Fair";
        }

        // If user password is greater than or equal to 8 character
        // and contains one Uppercase or one lowercase with a number and a special character
        if (strongStrength.test(str) && str.length >= 8)
        {
            changeColour(weak, "green");
            changeColour(fair, "green");
            changeColour(strong, "green");
            status.innerHTML = "Strong";
        }
    }
</script>

<?php require ('template/footer.phtml') ?>


