<?php require ('template/header.phtml')?>

<div class="button">
    <form action="auctionItem.php" method="post">
        <input type="submit" name="back" value="back" class="btn btn-danger">
    </form>
</div>
<br />
<form action="" method="post">
    <div class="card-header">
        <h3><?php echo 'Lot ID #' . $view->getItem[0]->getLotID() . ':'.  $view->getItem[0]->getLotTitle() .
                ' - ' .  $view->getItem[0]->getLotMain()?></h3>
    </div>
    <div class="row" style="padding: 10px; background-color: #e6e6e6">
        <div class="col-sm-4">
            <img src="images/<?php echo $view->getItem[0]->getImage()?>.jpg" alt="no image found" class="img-fluid">
            <input type="hidden" name="lotImage" value="<?php $view->getItem[0]->getImage() ?>">
        </div>

        <div class="col-sm-5">
            <p><?php echo $view->getItem[0]->getDescription()?></p>
            <p><b>Opening bid: </b>£<?php echo $view->getItem[0]->getPrice()?></p>

            <input id="lotID" type="hidden" name="lotID" value="<?php echo $view->getItem[0]->getLotID() ?>">
            <input type="hidden" name="lotTitle" value="<?php $view->getItem[0]->getLotTitle() ?>">
            <input type="hidden" name="lotMain" value="<?php $view->getItem[0]->getLotMain() ?>">
            <input type="hidden" name="lotDescription" value="<?php $view->getItem[0]->getDescription() ?>">
            <input type="hidden" name="lotPrice" value="<?php $view->getItem[0]->getPrice() ?>">
        </div>
        <div class="col-sm-3">
            <div class="page" style="text-align: center;">
                <h3><b><?php echo $view->getItem[0]->getAuctionName();?></b></h3>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                    </svg><b><?php echo $view->getItem[0]->getLocation(); ?></b></p>
                <p><b><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar3" viewBox="0 0 16 16">
                            <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                            <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                        </svg> <?php echo $view->getItem[0]->getDatetime() . " GMT"?></b></p>
                <p><b>Auctioneer: <?php echo $view->auctionItem->getAuctionAdmin($view->getItem[0]->getUserID())?></b></p>

                <input id="auctionID" type="hidden" name="auctionID" value="<?php echo $view->getItem[0]->getAuctionID() ?>">
                <input type="hidden" name="auctionName" value="<?php echo $view->getItem[0]->getAuctionName() ?>">
                <input type="hidden" name="auctionDatetime" value="<?php echo $view->getItem[0]->getDatetime() ?>">
                <input id="endDateTim" type="hidden" name="auctionEndDatetime" value="<?php echo $view->getItem[0]->getEndDatetime()?>">
                <input type="hidden" name="auctionAdmin" value="<?php echo $view->auctionItem->getAuctionAdmin($view->getItem[0]->getUserID()) ?>">
            </div>
        </div>
    </div>
</form>
    <br />
    <div class="row">
        <div class="col-sm-4">
            <div class="page">
                <b>Place your bid now!</b>
                    <?php if ($view->lotStatus) : ?>
                <div>
                        <p class="error"><b><?php echo $view->lotStatus?></b></p>
                </div>
                    <?php endif; ?>
                    <?php if (!$view->lotStatus) : ?>
                <div>
                <!--    <form action="" method="post">-->
                    <label>Your bid: £</label>
                    <input id="usrBid" type="text" name="userBid" placeholder="1000">
                    <input id="storeBid" type="hidden" name="userBidStore" placeholder="1000">
                    <div class="button" style="display: inline-block " onclick="LoadLotBids(<?php echo $_SESSION['viewLotID'] ?>, document.getElementById('bidContainer')); PlaceBid(document.getElementById('usrBid'), document.getElementById('bidError'))">
                        <!--<input id="bidButton" type="submit" name="place" value="Place" class="btn btn-primary">-->
                        <button id="bidButton" name="bidBtn" class="btn btn-primary">Place</button>

                        <p id="txt"></p>
                    </div>
                    <div>
                        <p id="bidError" class="error"><b><?php if (isset($view->userBidError))
                                    echo $view->userBidError?></b></p>
                        <?php if (isset($view->bidError))
                            echo $view->bidError?>
                        <br />
                    </div>
                </div>
                    <?php endif;?>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="row page">
                <div class="col-sm-4"><h4><b>Bid ID</b></h4></div>
                <div class="col-sm-4"><h4><b>Bidder</b></h4></div>
                <div class="col-sm-4"><h4><b>Bid</b></h4></div>
            </div>
            <form action="" method="post">
            <div id="bidContainer" class="">
                <?php
                if (isset($view->lotPrice))
                {
                    echo '<p><b>Opening bid £' . $view->lotPrice . '</b></p>';
                }

                if (isset($view->bidItemDataSet))
                {
                    if (!$view->bidItemData)
                    {
                        echo $view->emptyBidError;
                    }
                    else {
                        $num = 1;
                        foreach ($view->bidItemData as $bidItem) {
                            echo '<div id="bidRow' . $num .'" class="row dfContainer"><div id="idCol' . $num . '" class="col-sm-4">' . $bidItem->getBidID() .
                                '</div><div id="bidderCol1" class="col-sm-4">' . $view->bidItemDataSet->hideBidderName($bidItem->getUsername()) .
                                '</div><div id="bidCol1" class="col-sm-4">' . '£' . $bidItem->getBid() .
                                '</div></div>' .
                                '<input type="hidden" name="bidID" value="' . $bidItem->getBidID() . '">' .
                                '<input type="hidden" name="username" value="' . $bidItem->getUsername() . '">' .
                                '<input type="hidden" name="userPlacedBid" value="' . $bidItem->getBid() . '">';
                            $num++;
                        }
                    }
                }
                ?>

                <script type="text/javascript" src="js/loadLotBids.js"></script>
                <script type="text/javascript" src="js/placeBid.js"></script>
            </div>
        </div>
    </div>
</form>
<br />

<?php require ('template/footer.phtml')?>
