    </div>

    <!-- Footer -->
    <footer class="bg-dark text-center text-white">

        <div class="container p-4">
            <div class="row">
                <div class="ml-auto mr-auto">
                    <section class="mb-4">
                        <a class="btn btn-outline-light btn-floating m-1" href="#" role="button">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="btn btn-outline-light btn-floating m-1" href="#" role="button">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="btn btn-outline-light btn-floating m-1" href="#" role="button">
                            <i class="fab fa-google"></i>
                        </a>
                        <a class="btn btn-outline-light btn-floating m-1" href="#" role="button">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </section>

                    <section>

                    </section>
                </div>
            </div>
        </div>

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            <p class="text-white">Copyright &copy; Usman Shabir Kousar</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    </body>
    </html>